// use with VSC extension "Rest client" to execute API calls and inspect responses

### individual API key (use create api key below to generate)
# @api_key = AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
@api_key = VF9vcy0U1l19VQWYEKD+eeyX+RxuOLsj19EPuIWGc6A=

// WARNING: make sure to set the MASTER_KEY_SECRET environment variable to a secret, 
// otherwise your generated API keys will be compromised.
### create api key (use master API key displayed in the server console at startup)
POST http://127.0.0.1:80/api/v1/apikey HTTP/1.1
#apikey: A6xnQhbz4Vx2HuGl4lXwZ5U2I8iziLRFnhP5eNfIRvQ=
apikey: /iWStCpyfpd/BVlHOFtwnMgrFrmof4jGq/OQDWXQzcM=
content-type: application/json

{
    "indices_max": 10,
    "indices_size_max":100000, 
    "documents_max":10000000, 
    "operations_max":10000000, 
    "rate_limit": 100000
}

### delete api key
DELETE http://127.0.0.1/api/v1/apikey HTTP/1.1
apikey: {{api_key}}
content-type: application/json

### create index
POST http://127.0.0.1:80/api/v1/index HTTP/1.1
apikey: {{api_key}}
content-type: application/json

{
    "schema":[{
        "field": "title", 
        "field_type": "Text", 
        "stored": true, 
        "indexed": true,
        "boost":10.0
    },
        {
        "field": "body",
        "field_type": "Text", 
        "stored": true, 
        "indexed": true
    },
    {
        "field": "url", 
        "field_type": "String", 
        "stored": true, 
        "indexed": false
    }], 
    "index_name": "test_index",
    "similarity": "Bm25fProximity",
    "tokenizer": "UnicodeAlphanumeric"
}

### get index
GET http://127.0.0.1/api/v1/index/0 HTTP/1.1
apikey: {{api_key}}
content-type: application/json

### get all indexes (per apikey)

### get all indices (per server - requires master apikey)

### delete index
DELETE http://127.0.0.1/api/v1/index/0 HTTP/1.1
apikey: {{api_key}}
content-type: application/json

### commit index
PATCH http://127.0.0.1/api/v1/index/0 HTTP/1.1
apikey: {{api_key}}
content-type: application/json

### index document
POST http://127.0.0.1:80/api/v1/index/0/doc HTTP/1.1
apikey: {{api_key}}
content-type: application/json

{
    "title":"title1 test",
    "body":"body1",
    "url":"url1"
}

### index documents
POST http://127.0.0.1:80/api/v1/index/0/doc HTTP/1.1
apikey: {{api_key}}
content-type: application/json

[
{
    "title":"title2",
    "body":"body2 test",
    "url":"url2"
},
{
    "title":"title3 test",
    "body":"body3 test",
    "url":"url3"
}
]

### get documents with highlight
GET http://127.0.0.1/api/v1/index/0/doc/0 
apikey: {{api_key}}
content-type: application/json

//optional request body
{
    "query_terms": ["test"],
    "fields": ["title", "body"],
    "highlights": [
    { "field": "title", "fragment_number": 0, "fragment_size": 1000, "highlight_markup": true},
    { "field": "body", "fragment_number": 2, "fragment_size": 160, "highlight_markup": true},
    { "field": "body", "name": "body2", "fragment_number": 0, "fragment_size": 4000, "highlight_markup": true}]
}

### get document without highlight
GET http://127.0.0.1/api/v1/index/0/doc/0
apikey: {{api_key}}
content-type: application/json

### delete document, by single document ID in URL parameter
DELETE  http://127.0.0.1/api/v1/index/0/doc/0 HTTP/1.1
apikey: {{api_key}}
content-type: application/json


### delete document, by single document ID in JSON request object
DELETE  http://127.0.0.1/api/v1/index/0/doc HTTP/1.1
apikey: {{api_key}}
content-type: application/json

0

### delete documents, by vector of document IDs in JSON request object
DELETE  http://127.0.0.1/api/v1/index/0/doc HTTP/1.1
apikey: {{api_key}}
content-type: application/json

[
    0,
    1
]

### delete documents, by query in JSON request object
DELETE  http://127.0.0.1/api/v1/index/0/doc HTTP/1.1
apikey: {{api_key}}
content-type: application/json

{
    "query":"test",
    "offset":0,
    "length":10,
    "realtime": true,
    "field_filter": ["title", "body"]
}

### update document
PATCH  http://127.0.0.1/api/v1/index/0/doc HTTP/1.1
apikey: {{api_key}}
content-type: application/json

[0,{"title":"title1 test","body":"body1","url":"url1"}]

### update documents
PATCH  http://127.0.0.1/api/v1/index/0/doc HTTP/1.1
apikey: {{api_key}}
content-type: application/json

[[1,{"title":"title1 test","body":"body1","url":"url1"}],
[2,{"title":"title3 test","body":"body3 test","url":"url3"}]]

### query index GET
GET http://127.0.0.1/api/v1/index/0/query 
?query=test
&offset=0
&length=10
&realtime=true 
apikey: {{api_key}}
content-type: application/json

### query index GET with json request
GET http://127.0.0.1/api/v1/index/0/query 
apikey: {{api_key}}
content-type: application/json

{
    "query":"test",
    "offset":0,
    "length":10,
    "realtime": true,
    "field_filter": ["title", "body"]
}

### query index POST
POST http://127.0.0.1/api/v1/index/0/query HTTP/1.1
apikey: {{api_key}}
content-type: application/json

{
    "query":"test",
    "offset":0,
    "length":10,
    "result_type": "TopkCount",
    "realtime": true,
    "field_filter": ["title", "body"]
}

### query index POST with highlight
POST http://127.0.0.1/api/v1/index/0/query HTTP/1.1
apikey: {{api_key}}
content-type: application/json

{
    "query":"test",
    "offset":0,
    "length":10,
    "realtime": true,
    "highlights": [
    { "field": "title", "fragment_number": 0, "fragment_size": 1000, "highlight_markup": true},
    { "field": "body", "fragment_number": 2, "fragment_size": 160, "highlight_markup": true},
    { "field": "body", "name": "body2", "fragment_number": 0, "fragment_size": 4000, "highlight_markup": true}]
}

### create index NUMBER
POST http://127.0.0.1:80/api/v1/index HTTP/1.1
apikey: {{api_key}}
content-type: application/json

{
    "schema":[{
        "field": "title",
        "field_type": "Text", 
        "stored": true,  
        "indexed": true,
        "boost":10.0
    },
        {
        "field": "body", 
        "field_type": "Text", 
        "stored": true, 
        "indexed": true
    },
    {
        "field": "url", 
        "field_type": "String", 
        "stored": true, 
        "indexed": false
    },
    {
        "field": "number", 
        "field_type": "I64", 
        "stored": true, 
        "indexed": true
    }],
    "index_name": "test_index",
    "similarity": "Bm25fProximity",
    "tokenizer": "UnicodeAlphanumeric"
}

### index doc NUMBER
POST http://127.0.0.1:80/api/v1/index/0/doc HTTP/1.1
apikey: {{api_key}}
content-type: application/json

{
    "title":"title1 test",
    "body":"body1",
    "url":"url1",
    "number": 12345
}

### query index POST with highlight NUMBER
POST http://127.0.0.1/api/v1/index/0/query HTTP/1.1
apikey: {{api_key}}
content-type: application/json

{
    "query":"12345",
    "offset":0,
    "length":10,
    "realtime": true,
    "highlights": [
    { "field": "number", "name":"_number","fragment_number": 0, "fragment_size": 1000, "highlight_markup": true}]
}

// todo: other API endpoints